name: Deploy .NET API to AWS Elastic Beanstalk

on:
  workflow_dispatch:
  pull_request:
    types: cloesed
    branches:
      - main
    paths:
      - "Backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # Replace with your .NET version

    - name: Restore dependencies
      run: dotnet restore ./Backend

    - name: Build
      run: dotnet build ./Backend --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./Backend -c Release -o ./publish --no-restore

    - name: Compress deployment package
      run: zip -r ./deploy.zip ./publish/*

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
        EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
        CI: false
      run: |
        # Install the AWS Elastic Beanstalk CLI
        pip install awsebcli
        
        # Initialize the Elastic Beanstalk application
        eb init -p "dotnet-core" $EB_APPLICATION_NAME --region $AWS_REGION
        
        # Deploy to the Elastic Beanstalk environment
        eb deploy $EB_ENVIRONMENT_NAME --staged --label "${GITHUB_SHA::8}"
